import type { ReadingDay, Section } from '../types'

export const sections: Section[] = [
  { id: 'pentateuco', name: 'Pentateuco', color: '#d4a853', icon: 'scroll' },
  { id: 'historicos', name: 'Históricos', color: '#c0842f', icon: 'book-open' },
  { id: 'poeticos', name: 'Poéticos', color: '#f59e0b', icon: 'music' },
  { id: 'profetas', name: 'Profetas Maiores', color: '#dc2626', icon: 'message-square' },
  { id: 'menores', name: 'Profetas Menores', color: '#ef4444', icon: 'volume-2' },
  { id: 'evangelhos', name: 'Evangelhos', color: '#22c55e', icon: 'cross' },
  { id: 'atos-paulo', name: 'Atos & Paulo', color: '#3b82f6', icon: 'ship' },
  { id: 'cartas-paulo', name: 'Cartas de Paulo', color: '#6366f1', icon: 'mail' },
  { id: 'gerais', name: 'Cartas Gerais', color: '#a855f7', icon: 'bookmark' },
  { id: 'apocalipse', name: 'Apocalipse', color: '#f97316', icon: 'eye' },
]

const P = '◆' as const
const C = '•' as const

export const readingPlan: ReadingDay[] = [
  { day: 1,   book: 'Gênesis', bookNum: 1,  title: 'Gênesis 1–3',      chapters: '1–3',     section: sections[0], marker: P },
  { day: 2,   book: 'Gênesis', bookNum: 1,  title: 'Gênesis 4–6',      chapters: '4–6',     section: sections[0], marker: P },
  { day: 3,   book: 'Gênesis', bookNum: 1,  title: 'Gênesis 7–9',      chapters: '7–9',     section: sections[0], marker: P },
  { day: 4,   book: 'Gênesis', bookNum: 1,  title: 'Gênesis 10–12',    chapters: '10–12',   section: sections[0], marker: P },
  { day: 5,   book: 'Gênesis', bookNum: 1,  title: 'Gênesis 13–16',    chapters: '13–16',   section: sections[0], marker: P },
  { day: 6,   book: 'Gênesis', bookNum: 1,  title: 'Gênesis 17–20',    chapters: '17–20',   section: sections[0], marker: P },
  { day: 7,   book: 'Gênesis', bookNum: 1,  title: 'Gênesis 21–24',    chapters: '21–24',   section: sections[0], marker: P },
  { day: 8,   book: 'Gênesis', bookNum: 1,  title: 'Gênesis 25–27',    chapters: '25–27',   section: sections[0], marker: P },
  { day: 9,   book: 'Gênesis', bookNum: 1,  title: 'Gênesis 28–31',    chapters: '28–31',   section: sections[0], marker: P },
  { day: 10,  book: 'Gênesis', bookNum: 1,  title: 'Gênesis 32–35',    chapters: '32–35',   section: sections[0], marker: P },
  { day: 11,  book: 'Gênesis', bookNum: 1,  title: 'Gênesis 36–38',    chapters: '36–38',   section: sections[0], marker: P },
  { day: 12,  book: 'Gênesis', bookNum: 1,  title: 'Gênesis 39–42',    chapters: '39–42',   section: sections[0], marker: P },
  { day: 13,  book: 'Gênesis', bookNum: 1,  title: 'Gênesis 43–45',    chapters: '43–45',   section: sections[0], marker: P },
  { day: 14,  book: 'Gênesis', bookNum: 1,  title: 'Gênesis 46–48',    chapters: '46–48',   section: sections[0], marker: P },
  { day: 15,  book: 'Gênesis', bookNum: 1,  title: 'Gênesis 49–50',    chapters: '49–50',   section: sections[0], marker: P },
  { day: 16,  book: 'Êxodo', bookNum: 2,    title: 'Êxodo 1–3',        chapters: '1–3',     section: sections[0], marker: P },
  { day: 17,  book: 'Êxodo', bookNum: 2,    title: 'Êxodo 4–6',        chapters: '4–6',     section: sections[0], marker: P },
  { day: 18,  book: 'Êxodo', bookNum: 2,    title: 'Êxodo 7–9',        chapters: '7–9',     section: sections[0], marker: P },
  { day: 19,  book: 'Êxodo', bookNum: 2,    title: 'Êxodo 10–12',      chapters: '10–12',   section: sections[0], marker: P },
  { day: 20,  book: 'Êxodo', bookNum: 2,    title: 'Êxodo 13–15',      chapters: '13–15',   section: sections[0], marker: P },
  { day: 21,  book: 'Êxodo', bookNum: 2,    title: 'Êxodo 16–18',      chapters: '16–18',   section: sections[0], marker: P },
  { day: 22,  book: 'Êxodo', bookNum: 2,    title: 'Êxodo 19–21',      chapters: '19–21',   section: sections[0], marker: P },
  { day: 23,  book: 'Êxodo', bookNum: 2,    title: 'Êxodo 22–24',      chapters: '22–24',   section: sections[0], marker: P },
  { day: 24,  book: 'Êxodo', bookNum: 2,    title: 'Êxodo 25–27',      chapters: '25–27',   section: sections[0], marker: P },
  { day: 25,  book: 'Êxodo', bookNum: 2,    title: 'Êxodo 28–30',      chapters: '28–30',   section: sections[0], marker: P },
  { day: 26,  book: 'Êxodo', bookNum: 2,    title: 'Êxodo 31–34',      chapters: '31–34',   section: sections[0], marker: P },
  { day: 27,  book: 'Êxodo', bookNum: 2,    title: 'Êxodo 35–40',      chapters: '35–40',   section: sections[0], marker: P },
  { day: 28,  book: 'Levítico', bookNum: 3, title: 'Levítico 1–3',     chapters: '1–3',     section: sections[0], marker: P },
  { day: 29,  book: 'Levítico', bookNum: 3, title: 'Levítico 4–6',     chapters: '4–6',     section: sections[0], marker: P },
  { day: 30,  book: 'Levítico', bookNum: 3, title: 'Levítico 7–9',     chapters: '7–9',     section: sections[0], marker: P },
  { day: 31,  book: 'Levítico', bookNum: 3, title: 'Levítico 10–12',   chapters: '10–12',   section: sections[0], marker: P },
  { day: 32,  book: 'Levítico', bookNum: 3, title: 'Levítico 13–14',   chapters: '13–14',   section: sections[0], marker: P },
  { day: 33,  book: 'Levítico', bookNum: 3, title: 'Levítico 15–18',   chapters: '15–18',   section: sections[0], marker: P },
  { day: 34,  book: 'Levítico', bookNum: 3, title: 'Levítico 19–22',   chapters: '19–22',   section: sections[0], marker: P },
  { day: 35,  book: 'Levítico', bookNum: 3, title: 'Levítico 23–24',   chapters: '23–24',   section: sections[0], marker: P },
  { day: 36,  book: 'Levítico', bookNum: 3, title: 'Levítico 25–27',   chapters: '25–27',   section: sections[0], marker: P },
  { day: 37,  book: 'Números', bookNum: 4,  title: 'Números 1–3',      chapters: '1–3',     section: sections[0], marker: P },
  { day: 38,  book: 'Números', bookNum: 4,  title: 'Números 4–6',      chapters: '4–6',     section: sections[0], marker: P },
  { day: 39,  book: 'Números', bookNum: 4,  title: 'Números 7–10',     chapters: '7–10',    section: sections[0], marker: P },
  { day: 40,  book: 'Números', bookNum: 4,  title: 'Números 11–14',    chapters: '11–14',   section: sections[0], marker: P },
  { day: 41,  book: 'Números', bookNum: 4,  title: 'Números 15–18',    chapters: '15–18',   section: sections[0], marker: P },
  { day: 42,  book: 'Números', bookNum: 4,  title: 'Números 19–22',    chapters: '19–22',   section: sections[0], marker: P },
  { day: 43,  book: 'Números', bookNum: 4,  title: 'Números 23–27',    chapters: '23–27',   section: sections[0], marker: P },
  { day: 44,  book: 'Números', bookNum: 4,  title: 'Números 28–31',    chapters: '28–31',   section: sections[0], marker: P },
  { day: 45,  book: 'Números', bookNum: 4,  title: 'Números 32–36',    chapters: '32–36',   section: sections[0], marker: P },
  { day: 46,  book: 'Deuteronômio', bookNum: 5, title: 'Deuteronômio 1–4',  chapters: '1–4',   section: sections[0], marker: P },
  { day: 47,  book: 'Deuteronômio', bookNum: 5, title: 'Deuteronômio 5–7',  chapters: '5–7',   section: sections[0], marker: P },
  { day: 48,  book: 'Deuteronômio', bookNum: 5, title: 'Deuteronômio 8–11', chapters: '8–11',  section: sections[0], marker: P },
  { day: 49,  book: 'Deuteronômio', bookNum: 5, title: 'Deuteronômio 12–15', chapters: '12–15', section: sections[0], marker: P },
  { day: 50,  book: 'Deuteronômio', bookNum: 5, title: 'Deuteronômio 16–19', chapters: '16–19', section: sections[0], marker: P },
  { day: 51,  book: 'Deuteronômio', bookNum: 5, title: 'Deuteronômio 20–23', chapters: '20–23', section: sections[0], marker: P },
  { day: 52,  book: 'Deuteronômio', bookNum: 5, title: 'Deuteronômio 24–27', chapters: '24–27', section: sections[0], marker: P },
  { day: 53,  book: 'Deuteronômio', bookNum: 5, title: 'Deuteronômio 28–30', chapters: '28–30', section: sections[0], marker: P },
  { day: 54,  book: 'Deuteronômio', bookNum: 5, title: 'Deuteronômio 31–34', chapters: '31–34', section: sections[0], marker: P },
  { day: 55,  book: 'Josué', bookNum: 6,     title: 'Josué 1–4',        chapters: '1–4',     section: sections[1], marker: P },
  { day: 56,  book: 'Josué', bookNum: 6,     title: 'Josué 5–8',        chapters: '5–8',     section: sections[1], marker: P },
  { day: 57,  book: 'Josué', bookNum: 6,     title: 'Josué 9–12',       chapters: '9–12',    section: sections[1], marker: P },
  { day: 58,  book: 'Josué', bookNum: 6,     title: 'Josué 13–16',      chapters: '13–16',   section: sections[1], marker: P },
  { day: 59,  book: 'Josué', bookNum: 6,     title: 'Josué 17–21',      chapters: '17–21',   section: sections[1], marker: P },
  { day: 60,  book: 'Josué', bookNum: 6,     title: 'Josué 22–24',      chapters: '22–24',   section: sections[1], marker: P },
  { day: 61,  book: 'Juízes', bookNum: 7,    title: 'Juízes 1–4',       chapters: '1–4',     section: sections[1], marker: P },
  { day: 62,  book: 'Juízes', bookNum: 7,    title: 'Juízes 5–8',       chapters: '5–8',     section: sections[1], marker: P },
  { day: 63,  book: 'Juízes', bookNum: 7,    title: 'Juízes 9–12',      chapters: '9–12',    section: sections[1], marker: P },
  { day: 64,  book: 'Juízes', bookNum: 7,    title: 'Juízes 13–16',     chapters: '13–16',   section: sections[1], marker: P },
  { day: 65,  book: 'Juízes', bookNum: 7,    title: 'Juízes 17–21',     chapters: '17–21',   section: sections[1], marker: P },
  { day: 66,  book: 'Rute', bookNum: 8,      title: 'Rute 1–4',         chapters: '1–4',     section: sections[1], marker: P },
  { day: 67,  book: '1 Samuel', bookNum: 9,  title: '1 Samuel 1–4',     chapters: '1–4',     section: sections[1], marker: P },
  { day: 68,  book: '1 Samuel', bookNum: 9,  title: '1 Samuel 5–8',     chapters: '5–8',     section: sections[1], marker: P },
  { day: 69,  book: '1 Samuel', bookNum: 9,  title: '1 Samuel 9–12',    chapters: '9–12',    section: sections[1], marker: P },
  { day: 70,  book: '1 Samuel', bookNum: 9,  title: '1 Samuel 13–16',   chapters: '13–16',   section: sections[1], marker: P },
  { day: 71,  book: '1 Samuel', bookNum: 9,  title: '1 Samuel 17–20',   chapters: '17–20',   section: sections[1], marker: P },
  { day: 72,  book: '1 Samuel', bookNum: 9,  title: '1 Samuel 21–25',   chapters: '21–25',   section: sections[1], marker: P },
  { day: 73,  book: '1 Samuel', bookNum: 9,  title: '1 Samuel 26–28',   chapters: '26–28',   section: sections[1], marker: P },
  { day: 74,  book: '1 Samuel', bookNum: 9,  title: '1 Samuel 29–31',   chapters: '29–31',   section: sections[1], marker: P },
  { day: 75,  book: '2 Samuel', bookNum: 10, title: '2 Samuel 1–4',     chapters: '1–4',     section: sections[1], marker: P },
  { day: 76,  book: '2 Samuel', bookNum: 10, title: '2 Samuel 5–8',     chapters: '5–8',     section: sections[1], marker: P },
  { day: 77,  book: '2 Samuel', bookNum: 10, title: '2 Samuel 9–12',    chapters: '9–12',    section: sections[1], marker: P },
  { day: 78,  book: '2 Samuel', bookNum: 10, title: '2 Samuel 13–15',   chapters: '13–15',   section: sections[1], marker: P },
  { day: 79,  book: '2 Samuel', bookNum: 10, title: '2 Samuel 16–18',   chapters: '16–18',   section: sections[1], marker: P },
  { day: 80,  book: '2 Samuel', bookNum: 10, title: '2 Samuel 19–21',   chapters: '19–21',   section: sections[1], marker: P },
  { day: 81,  book: '2 Samuel', bookNum: 10, title: '2 Samuel 22–24',   chapters: '22–24',   section: sections[1], marker: P },
  { day: 82,  book: '1 Reis', bookNum: 11,   title: '1 Reis 1–4',       chapters: '1–4',     section: sections[1], marker: P },
  { day: 83,  book: '1 Reis', bookNum: 11,   title: '1 Reis 5–8',       chapters: '5–8',     section: sections[1], marker: P },
  { day: 84,  book: '1 Reis', bookNum: 11,   title: '1 Reis 9–11',      chapters: '9–11',    section: sections[1], marker: P },
  { day: 85,  book: '1 Reis', bookNum: 11,   title: '1 Reis 12–15',     chapters: '12–15',   section: sections[1], marker: P },
  { day: 86,  book: '1 Reis', bookNum: 11,   title: '1 Reis 16–18',     chapters: '16–18',   section: sections[1], marker: P },
  { day: 87,  book: '1 Reis', bookNum: 11,   title: '1 Reis 19–22',     chapters: '19–22',   section: sections[1], marker: P },
  { day: 88,  book: '2 Reis', bookNum: 12,   title: '2 Reis 1–5',       chapters: '1–5',     section: sections[1], marker: P },
  { day: 89,  book: '2 Reis', bookNum: 12,   title: '2 Reis 6–9',       chapters: '6–9',     section: sections[1], marker: P },
  { day: 90,  book: '2 Reis', bookNum: 12,   title: '2 Reis 10–13',     chapters: '10–13',   section: sections[1], marker: P },
  { day: 91,  book: '2 Reis', bookNum: 12,   title: '2 Reis 14–17',     chapters: '14–17',   section: sections[1], marker: P },
  { day: 92,  book: '2 Reis', bookNum: 12,   title: '2 Reis 18–21',     chapters: '18–21',   section: sections[1], marker: P },
  { day: 93,  book: '2 Reis', bookNum: 12,   title: '2 Reis 22–25',     chapters: '22–25',   section: sections[1], marker: P },
  { day: 94,  book: '1 Crônicas', bookNum: 13, title: '1 Crônicas 1–5', chapters: '1–5',     section: sections[1], marker: P },
  { day: 95,  book: '1 Crônicas', bookNum: 13, title: '1 Crônicas 6–10', chapters: '6–10',   section: sections[1], marker: P },
  { day: 96,  book: '1 Crônicas', bookNum: 13, title: '1 Crônicas 11–15', chapters: '11–15', section: sections[1], marker: P },
  { day: 97,  book: '1 Crônicas', bookNum: 13, title: '1 Crônicas 16–21', chapters: '16–21', section: sections[1], marker: P },
  { day: 98,  book: '1 Crônicas', bookNum: 13, title: '1 Crônicas 22–26', chapters: '22–26', section: sections[1], marker: P },
  { day: 99,  book: '1 Crônicas', bookNum: 13, title: '1 Crônicas 27–29', chapters: '27–29', section: sections[1], marker: P },
  { day: 100, book: '2 Crônicas', bookNum: 14, title: '2 Crônicas 1–5', chapters: '1–5',     section: sections[1], marker: P },
  { day: 101, book: '2 Crônicas', bookNum: 14, title: '2 Crônicas 6–10', chapters: '6–10',   section: sections[1], marker: P },
  { day: 102, book: '2 Crônicas', bookNum: 14, title: '2 Crônicas 11–15', chapters: '11–15', section: sections[1], marker: P },
  { day: 103, book: '2 Crônicas', bookNum: 14, title: '2 Crônicas 16–21', chapters: '16–21', section: sections[1], marker: P },
  { day: 104, book: '2 Crônicas', bookNum: 14, title: '2 Crônicas 22–26', chapters: '22–26', section: sections[1], marker: P },
  { day: 105, book: '2 Crônicas', bookNum: 14, title: '2 Crônicas 27–31', chapters: '27–31', section: sections[1], marker: P },
  { day: 106, book: '2 Crônicas', bookNum: 14, title: '2 Crônicas 32–36', chapters: '32–36', section: sections[1], marker: P },
  { day: 107, book: 'Esdras', bookNum: 15,  title: 'Esdras 1–4',        chapters: '1–4',     section: sections[1], marker: P },
  { day: 108, book: 'Esdras', bookNum: 15,  title: 'Esdras 5–10',       chapters: '5–10',    section: sections[1], marker: P },
  { day: 109, book: 'Neemias', bookNum: 16, title: 'Neemias 1–5',       chapters: '1–5',     section: sections[1], marker: P },
  { day: 110, book: 'Neemias', bookNum: 16, title: 'Neemias 6–9',       chapters: '6–9',     section: sections[1], marker: P },
  { day: 111, book: 'Neemias', bookNum: 16, title: 'Neemias 10–13',     chapters: '10–13',   section: sections[1], marker: P },
  { day: 112, book: 'Ester', bookNum: 17,   title: 'Ester 1–5',         chapters: '1–5',     section: sections[1], marker: P },
  { day: 113, book: 'Ester', bookNum: 17,   title: 'Ester 6–10',        chapters: '6–10',    section: sections[1], marker: P },
  { day: 114, book: 'Jó', bookNum: 18,      title: 'Jó 1–5',            chapters: '1–5',     section: sections[2], marker: P },
  { day: 115, book: 'Jó', bookNum: 18,      title: 'Jó 6–10',           chapters: '6–10',    section: sections[2], marker: P },
  { day: 116, book: 'Jó', bookNum: 18,      title: 'Jó 11–15',          chapters: '11–15',   section: sections[2], marker: P },
  { day: 117, book: 'Jó', bookNum: 18,      title: 'Jó 16–21',          chapters: '16–21',   section: sections[2], marker: P },
  { day: 118, book: 'Jó', bookNum: 18,      title: 'Jó 22–28',          chapters: '22–28',   section: sections[2], marker: P },
  { day: 119, book: 'Jó', bookNum: 18,      title: 'Jó 29–34',          chapters: '29–34',   section: sections[2], marker: P },
  { day: 120, book: 'Jó', bookNum: 18,      title: 'Jó 35–39',          chapters: '35–39',   section: sections[2], marker: P },
  { day: 121, book: 'Jó', bookNum: 18,      title: 'Jó 40–42',          chapters: '40–42',   section: sections[2], marker: P },
  { day: 122, book: 'Salmos', bookNum: 19,  title: 'Salmos 1–6',        chapters: '1–6',     section: sections[2], marker: P },
  { day: 123, book: 'Salmos', bookNum: 19,  title: 'Salmos 7–11',       chapters: '7–11',    section: sections[2], marker: P },
  { day: 124, book: 'Salmos', bookNum: 19,  title: 'Salmos 12–17',      chapters: '12–17',   section: sections[2], marker: P },
  { day: 125, book: 'Salmos', bookNum: 19,  title: 'Salmos 18–22',      chapters: '18–22',   section: sections[2], marker: P },
  { day: 126, book: 'Salmos', bookNum: 19,  title: 'Salmos 23–28',      chapters: '23–28',   section: sections[2], marker: P },
  { day: 127, book: 'Salmos', bookNum: 19,  title: 'Salmos 29–34',      chapters: '29–34',   section: sections[2], marker: P },
  { day: 128, book: 'Salmos', bookNum: 19,  title: 'Salmos 35–39',      chapters: '35–39',   section: sections[2], marker: P },
  { day: 129, book: 'Salmos', bookNum: 19,  title: 'Salmos 40–45',      chapters: '40–45',   section: sections[2], marker: P },
  { day: 130, book: 'Salmos', bookNum: 19,  title: 'Salmos 46–51',      chapters: '46–51',   section: sections[2], marker: P },
  { day: 131, book: 'Salmos', bookNum: 19,  title: 'Salmos 52–59',      chapters: '52–59',   section: sections[2], marker: P },
  { day: 132, book: 'Salmos', bookNum: 19,  title: 'Salmos 60–66',      chapters: '60–66',   section: sections[2], marker: P },
  { day: 133, book: 'Salmos', bookNum: 19,  title: 'Salmos 67–72',      chapters: '67–72',   section: sections[2], marker: P },
  { day: 134, book: 'Salmos', bookNum: 19,  title: 'Salmos 73–78',      chapters: '73–78',   section: sections[2], marker: P },
  { day: 135, book: 'Salmos', bookNum: 19,  title: 'Salmos 79–84',      chapters: '79–84',   section: sections[2], marker: P },
  { day: 136, book: 'Salmos', bookNum: 19,  title: 'Salmos 85–90',      chapters: '85–90',   section: sections[2], marker: P },
  { day: 137, book: 'Salmos', bookNum: 19,  title: 'Salmos 91–98',      chapters: '91–98',   section: sections[2], marker: P },
  { day: 138, book: 'Salmos', bookNum: 19,  title: 'Salmos 99–104',     chapters: '99–104',  section: sections[2], marker: P },
  { day: 139, book: 'Salmos', bookNum: 19,  title: 'Salmos 105–108',    chapters: '105–108', section: sections[2], marker: P },
  { day: 140, book: 'Salmos', bookNum: 19,  title: 'Salmos 109–113',    chapters: '109–113', section: sections[2], marker: P },
  { day: 141, book: 'Salmos', bookNum: 19,  title: 'Salmos 114–119',    chapters: '114–119', section: sections[2], marker: P },
  { day: 142, book: 'Salmos', bookNum: 19,  title: 'Salmos 120–126',    chapters: '120–126', section: sections[2], marker: P },
  { day: 143, book: 'Salmos', bookNum: 19,  title: 'Salmos 127–132',    chapters: '127–132', section: sections[2], marker: P },
  { day: 144, book: 'Salmos', bookNum: 19,  title: 'Salmos 133–139',    chapters: '133–139', section: sections[2], marker: P },
  { day: 145, book: 'Salmos', bookNum: 19,  title: 'Salmos 140–145',    chapters: '140–145', section: sections[2], marker: P },
  { day: 146, book: 'Salmos', bookNum: 19,  title: 'Salmos 146–150',    chapters: '146–150', section: sections[2], marker: P },
  { day: 147, book: 'Provérbios', bookNum: 20, title: 'Provérbios 1–4', chapters: '1–4',     section: sections[2], marker: P },
  { day: 148, book: 'Provérbios', bookNum: 20, title: 'Provérbios 5–9', chapters: '5–9',     section: sections[2], marker: P },
  { day: 149, book: 'Provérbios', bookNum: 20, title: 'Provérbios 10–13', chapters: '10–13', section: sections[2], marker: P },
  { day: 150, book: 'Provérbios', bookNum: 20, title: 'Provérbios 14–18', chapters: '14–18', section: sections[2], marker: P },
  { day: 151, book: 'Provérbios', bookNum: 20, title: 'Provérbios 19–22', chapters: '19–22', section: sections[2], marker: P },
  { day: 152, book: 'Provérbios', bookNum: 20, title: 'Provérbios 23–26', chapters: '23–26', section: sections[2], marker: P },
  { day: 153, book: 'Provérbios', bookNum: 20, title: 'Provérbios 27–31', chapters: '27–31', section: sections[2], marker: P },
  { day: 154, book: 'Eclesiastes', bookNum: 21, title: 'Eclesiastes 1–6', chapters: '1–6',   section: sections[2], marker: P },
  { day: 155, book: 'Eclesiastes', bookNum: 21, title: 'Eclesiastes 7–12', chapters: '7–12', section: sections[2], marker: P },
  { day: 156, book: 'Cântico de Salomão', bookNum: 22, title: 'Cântico de Salomão 1–8', chapters: '1–8', section: sections[2], marker: P },
  { day: 157, book: 'Isaías', bookNum: 23,  title: 'Isaías 1–5',        chapters: '1–5',     section: sections[3], marker: P },
  { day: 158, book: 'Isaías', bookNum: 23,  title: 'Isaías 6–10',       chapters: '6–10',    section: sections[3], marker: P },
  { day: 159, book: 'Isaías', bookNum: 23,  title: 'Isaías 11–16',      chapters: '11–16',   section: sections[3], marker: P },
  { day: 160, book: 'Isaías', bookNum: 23,  title: 'Isaías 17–22',      chapters: '17–22',   section: sections[3], marker: P },
  { day: 161, book: 'Isaías', bookNum: 23,  title: 'Isaías 23–28',      chapters: '23–28',   section: sections[3], marker: P },
  { day: 162, book: 'Isaías', bookNum: 23,  title: 'Isaías 29–34',      chapters: '29–34',   section: sections[3], marker: P },
  { day: 163, book: 'Isaías', bookNum: 23,  title: 'Isaías 35–40',      chapters: '35–40',   section: sections[3], marker: P },
  { day: 164, book: 'Isaías', bookNum: 23,  title: 'Isaías 41–45',      chapters: '41–45',   section: sections[3], marker: P },
  { day: 165, book: 'Isaías', bookNum: 23,  title: 'Isaías 46–51',      chapters: '46–51',   section: sections[3], marker: P },
  { day: 166, book: 'Isaías', bookNum: 23,  title: 'Isaías 52–57',      chapters: '52–57',   section: sections[3], marker: P },
  { day: 167, book: 'Isaías', bookNum: 23,  title: 'Isaías 58–62',      chapters: '58–62',   section: sections[3], marker: P },
  { day: 168, book: 'Isaías', bookNum: 23,  title: 'Isaías 63–66',      chapters: '63–66',   section: sections[3], marker: P },
  { day: 169, book: 'Jeremias', bookNum: 24, title: 'Jeremias 1–5',     chapters: '1–5',     section: sections[3], marker: P },
  { day: 170, book: 'Jeremias', bookNum: 24, title: 'Jeremias 6–10',    chapters: '6–10',    section: sections[3], marker: P },
  { day: 171, book: 'Jeremias', bookNum: 24, title: 'Jeremias 11–15',   chapters: '11–15',   section: sections[3], marker: P },
  { day: 172, book: 'Jeremias', bookNum: 24, title: 'Jeremias 16–20',   chapters: '16–20',   section: sections[3], marker: P },
  { day: 173, book: 'Jeremias', bookNum: 24, title: 'Jeremias 21–25',   chapters: '21–25',   section: sections[3], marker: P },
  { day: 174, book: 'Jeremias', bookNum: 24, title: 'Jeremias 26–29',   chapters: '26–29',   section: sections[3], marker: P },
  { day: 175, book: 'Jeremias', bookNum: 24, title: 'Jeremias 30–33',   chapters: '30–33',   section: sections[3], marker: P },
  { day: 176, book: 'Jeremias', bookNum: 24, title: 'Jeremias 34–38',   chapters: '34–38',   section: sections[3], marker: P },
  { day: 177, book: 'Jeremias', bookNum: 24, title: 'Jeremias 39–44',   chapters: '39–44',   section: sections[3], marker: P },
  { day: 178, book: 'Jeremias', bookNum: 24, title: 'Jeremias 45–48',   chapters: '45–48',   section: sections[3], marker: P },
  { day: 179, book: 'Jeremias', bookNum: 24, title: 'Jeremias 49–52',   chapters: '49–52',   section: sections[3], marker: P },
  { day: 180, book: 'Lamentações', bookNum: 25, title: 'Lamentações 1–5', chapters: '1–5',  section: sections[3], marker: P },
  { day: 181, book: 'Ezequiel', bookNum: 26, title: 'Ezequiel 1–5',     chapters: '1–5',     section: sections[3], marker: P },
  { day: 182, book: 'Ezequiel', bookNum: 26, title: 'Ezequiel 6–10',    chapters: '6–10',    section: sections[3], marker: P },
  { day: 183, book: 'Ezequiel', bookNum: 26, title: 'Ezequiel 11–16',   chapters: '11–16',   section: sections[3], marker: P },
  { day: 184, book: 'Ezequiel', bookNum: 26, title: 'Ezequiel 17–22',   chapters: '17–22',   section: sections[3], marker: P },
  { day: 185, book: 'Ezequiel', bookNum: 26, title: 'Ezequiel 23–27',   chapters: '23–27',   section: sections[3], marker: P },
  { day: 186, book: 'Ezequiel', bookNum: 26, title: 'Ezequiel 28–33',   chapters: '28–33',   section: sections[3], marker: P },
  { day: 187, book: 'Ezequiel', bookNum: 26, title: 'Ezequiel 34–39',   chapters: '34–39',   section: sections[3], marker: P },
  { day: 188, book: 'Ezequiel', bookNum: 26, title: 'Ezequiel 40–44',   chapters: '40–44',   section: sections[3], marker: P },
  { day: 189, book: 'Ezequiel', bookNum: 26, title: 'Ezequiel 45–48',   chapters: '45–48',   section: sections[3], marker: P },
  { day: 190, book: 'Daniel', bookNum: 27,  title: 'Daniel 1–4',        chapters: '1–4',     section: sections[3], marker: P },
  { day: 191, book: 'Daniel', bookNum: 27,  title: 'Daniel 5–8',        chapters: '5–8',     section: sections[3], marker: P },
  { day: 192, book: 'Daniel', bookNum: 27,  title: 'Daniel 9–12',       chapters: '9–12',    section: sections[3], marker: P },
  { day: 193, book: 'Oseias', bookNum: 28,  title: 'Oseias 1–7',        chapters: '1–7',     section: sections[4], marker: P },
  { day: 194, book: 'Oseias', bookNum: 28,  title: 'Oseias 8–14',       chapters: '8–14',    section: sections[4], marker: P },
  { day: 195, book: 'Joel', bookNum: 29,    title: 'Joel 1–3',          chapters: '1–3',     section: sections[4], marker: P },
  { day: 196, book: 'Amós', bookNum: 30,    title: 'Amós 1–5',          chapters: '1–5',     section: sections[4], marker: P },
  { day: 197, book: 'Amós', bookNum: 30,    title: 'Amós 6–9',          chapters: '6–9',     section: sections[4], marker: P },
  { day: 198, book: 'Obadias', bookNum: 31, title: 'Obadias',            chapters: '1',       section: sections[4], marker: P },
  { day: 198, book: 'Jonas', bookNum: 32,   title: 'Jonas 1–4',         chapters: '1–4',     section: sections[4], marker: P },
  { day: 199, book: 'Miqueias', bookNum: 33, title: 'Miqueias 1–7',    chapters: '1–7',     section: sections[4], marker: P },
  { day: 200, book: 'Naum', bookNum: 34,    title: 'Naum 1–3',          chapters: '1–3',     section: sections[4], marker: P },
  { day: 200, book: 'Habacuque', bookNum: 35, title: 'Habacuque 1–3',  chapters: '1–3',     section: sections[4], marker: P },
  { day: 201, book: 'Sofonias', bookNum: 36, title: 'Sofonias 1–3',    chapters: '1–3',     section: sections[4], marker: P },
  { day: 201, book: 'Ageu', bookNum: 37,    title: 'Ageu 1–2',          chapters: '1–2',     section: sections[4], marker: P },
  { day: 202, book: 'Zacarias', bookNum: 38, title: 'Zacarias 1–5',    chapters: '1–5',     section: sections[4], marker: P },
  { day: 203, book: 'Zacarias', bookNum: 38, title: 'Zacarias 6–10',   chapters: '6–10',    section: sections[4], marker: P },
  { day: 204, book: 'Zacarias', bookNum: 38, title: 'Zacarias 11–14',  chapters: '11–14',   section: sections[4], marker: P },
  { day: 205, book: 'Malaquias', bookNum: 39, title: 'Malaquias 1–4',  chapters: '1–4',     section: sections[4], marker: P },
  { day: 206, book: 'Mateus', bookNum: 40,  title: 'Mateus 1–4',        chapters: '1–4',     section: sections[5], marker: C },
  { day: 207, book: 'Mateus', bookNum: 40,  title: 'Mateus 5–7',        chapters: '5–7',     section: sections[5], marker: C },
  { day: 208, book: 'Mateus', bookNum: 40,  title: 'Mateus 8–10',       chapters: '8–10',    section: sections[5], marker: C },
  { day: 209, book: 'Mateus', bookNum: 40,  title: 'Mateus 11–13',      chapters: '11–13',   section: sections[5], marker: C },
  { day: 210, book: 'Mateus', bookNum: 40,  title: 'Mateus 14–16',      chapters: '14–16',   section: sections[5], marker: C },
  { day: 211, book: 'Mateus', bookNum: 40,  title: 'Mateus 17–19',      chapters: '17–19',   section: sections[5], marker: C },
  { day: 212, book: 'Mateus', bookNum: 40,  title: 'Mateus 20–22',      chapters: '20–22',   section: sections[5], marker: C },
  { day: 213, book: 'Mateus', bookNum: 40,  title: 'Mateus 23–25',      chapters: '23–25',   section: sections[5], marker: C },
  { day: 214, book: 'Mateus', bookNum: 40,  title: 'Mateus 26–28',      chapters: '26–28',   section: sections[5], marker: C },
  { day: 215, book: 'Marcos', bookNum: 41,  title: 'Marcos 1–3',        chapters: '1–3',     section: sections[5], marker: C },
  { day: 216, book: 'Marcos', bookNum: 41,  title: 'Marcos 4–6',        chapters: '4–6',     section: sections[5], marker: C },
  { day: 217, book: 'Marcos', bookNum: 41,  title: 'Marcos 7–9',        chapters: '7–9',     section: sections[5], marker: C },
  { day: 218, book: 'Marcos', bookNum: 41,  title: 'Marcos 10–12',      chapters: '10–12',   section: sections[5], marker: C },
  { day: 219, book: 'Marcos', bookNum: 41,  title: 'Marcos 13–16',      chapters: '13–16',   section: sections[5], marker: C },
  { day: 220, book: 'Lucas', bookNum: 42,   title: 'Lucas 1–3',         chapters: '1–3',     section: sections[5], marker: C },
  { day: 221, book: 'Lucas', bookNum: 42,   title: 'Lucas 4–6',         chapters: '4–6',     section: sections[5], marker: C },
  { day: 222, book: 'Lucas', bookNum: 42,   title: 'Lucas 7–9',         chapters: '7–9',     section: sections[5], marker: C },
  { day: 223, book: 'Lucas', bookNum: 42,   title: 'Lucas 10–12',       chapters: '10–12',   section: sections[5], marker: C },
  { day: 224, book: 'Lucas', bookNum: 42,   title: 'Lucas 13–16',       chapters: '13–16',   section: sections[5], marker: C },
  { day: 225, book: 'Lucas', bookNum: 42,   title: 'Lucas 17–20',       chapters: '17–20',   section: sections[5], marker: C },
  { day: 226, book: 'Lucas', bookNum: 42,   title: 'Lucas 21–24',       chapters: '21–24',   section: sections[5], marker: C },
  { day: 227, book: 'João', bookNum: 43,    title: 'João 1–3',          chapters: '1–3',     section: sections[5], marker: C },
  { day: 228, book: 'João', bookNum: 43,    title: 'João 4–6',          chapters: '4–6',     section: sections[5], marker: C },
  { day: 229, book: 'João', bookNum: 43,    title: 'João 7–9',          chapters: '7–9',     section: sections[5], marker: C },
  { day: 230, book: 'João', bookNum: 43,    title: 'João 10–12',        chapters: '10–12',   section: sections[5], marker: C },
  { day: 231, book: 'João', bookNum: 43,    title: 'João 13–15',        chapters: '13–15',   section: sections[5], marker: C },
  { day: 232, book: 'João', bookNum: 43,    title: 'João 16–18',        chapters: '16–18',   section: sections[5], marker: C },
  { day: 233, book: 'João', bookNum: 43,    title: 'João 19–21',        chapters: '19–21',   section: sections[5], marker: C },
  { day: 234, book: 'Atos', bookNum: 44,    title: 'Atos 1–4',          chapters: '1–4',     section: sections[6], marker: C },
  { day: 235, book: 'Atos', bookNum: 44,    title: 'Atos 5–8',          chapters: '5–8',     section: sections[6], marker: C },
  { day: 236, book: 'Atos', bookNum: 44,    title: 'Atos 9–12',         chapters: '9–12',    section: sections[6], marker: C },
  { day: 237, book: 'Atos', bookNum: 44,    title: 'Atos 13–16',        chapters: '13–16',   section: sections[6], marker: C },
  { day: 238, book: 'Atos', bookNum: 44,    title: 'Atos 17–20',        chapters: '17–20',   section: sections[6], marker: C },
  { day: 239, book: 'Atos', bookNum: 44,    title: 'Atos 21–24',        chapters: '21–24',   section: sections[6], marker: C },
  { day: 240, book: 'Atos', bookNum: 44,    title: 'Atos 25–28',        chapters: '25–28',   section: sections[6], marker: C },
  { day: 241, book: 'Romanos', bookNum: 45, title: 'Romanos 1–4',       chapters: '1–4',     section: sections[6], marker: C },
  { day: 242, book: 'Romanos', bookNum: 45, title: 'Romanos 5–8',       chapters: '5–8',     section: sections[6], marker: C },
  { day: 243, book: 'Romanos', bookNum: 45, title: 'Romanos 9–12',      chapters: '9–12',    section: sections[6], marker: C },
  { day: 244, book: 'Romanos', bookNum: 45, title: 'Romanos 13–16',     chapters: '13–16',   section: sections[6], marker: C },
  { day: 245, book: '1 Coríntios', bookNum: 46, title: '1 Coríntios 1–4', chapters: '1–4',   section: sections[7], marker: C },
  { day: 246, book: '1 Coríntios', bookNum: 46, title: '1 Coríntios 5–8', chapters: '5–8',   section: sections[7], marker: C },
  { day: 247, book: '1 Coríntios', bookNum: 46, title: '1 Coríntios 9–11', chapters: '9–11', section: sections[7], marker: C },
  { day: 248, book: '1 Coríntios', bookNum: 46, title: '1 Coríntios 12–14', chapters: '12–14', section: sections[7], marker: C },
  { day: 249, book: '1 Coríntios', bookNum: 46, title: '1 Coríntios 15–16', chapters: '15–16', section: sections[7], marker: C },
  { day: 250, book: '2 Coríntios', bookNum: 47, title: '2 Coríntios 1–4', chapters: '1–4',   section: sections[7], marker: C },
  { day: 251, book: '2 Coríntios', bookNum: 47, title: '2 Coríntios 5–9', chapters: '5–9',   section: sections[7], marker: C },
  { day: 252, book: '2 Coríntios', bookNum: 47, title: '2 Coríntios 10–13', chapters: '10–13', section: sections[7], marker: C },
  { day: 253, book: 'Gálatas', bookNum: 48,  title: 'Gálatas 1–3',       chapters: '1–3',     section: sections[7], marker: C },
  { day: 254, book: 'Gálatas', bookNum: 48,  title: 'Gálatas 4–6',       chapters: '4–6',     section: sections[7], marker: C },
  { day: 255, book: 'Efésios', bookNum: 49,  title: 'Efésios 1–3',       chapters: '1–3',     section: sections[7], marker: C },
  { day: 256, book: 'Efésios', bookNum: 49,  title: 'Efésios 4–6',       chapters: '4–6',     section: sections[7], marker: C },
  { day: 257, book: 'Filipenses', bookNum: 50, title: 'Filipenses 1–2',  chapters: '1–2',     section: sections[7], marker: C },
  { day: 258, book: 'Filipenses', bookNum: 50, title: 'Filipenses 3–4',  chapters: '3–4',     section: sections[7], marker: C },
  { day: 259, book: 'Colossenses', bookNum: 51, title: 'Colossenses 1–2', chapters: '1–2',    section: sections[7], marker: C },
  { day: 260, book: 'Colossenses', bookNum: 51, title: 'Colossenses 3–4', chapters: '3–4',    section: sections[7], marker: C },
  { day: 261, book: '1 Tessalonicenses', bookNum: 52, title: '1 Tessalonicenses 1–5', chapters: '1–5', section: sections[7], marker: C },
  { day: 262, book: '2 Tessalonicenses', bookNum: 53, title: '2 Tessalonicenses 1–3', chapters: '1–3', section: sections[7], marker: C },
  { day: 263, book: '1 Timóteo', bookNum: 54, title: '1 Timóteo 1–3',   chapters: '1–3',     section: sections[7], marker: C },
  { day: 264, book: '1 Timóteo', bookNum: 54, title: '1 Timóteo 4–6',   chapters: '4–6',     section: sections[7], marker: C },
  { day: 265, book: '2 Timóteo', bookNum: 55, title: '2 Timóteo 1–4',   chapters: '1–4',     section: sections[7], marker: C },
  { day: 266, book: 'Tito', bookNum: 56,    title: 'Tito 1–3',          chapters: '1–3',     section: sections[7], marker: C },
  { day: 266, book: 'Filemom', bookNum: 57, title: 'Filemom',            chapters: '1',       section: sections[7], marker: C },
  { day: 267, book: 'Hebreus', bookNum: 58, title: 'Hebreus 1–4',       chapters: '1–4',     section: sections[8], marker: C },
  { day: 268, book: 'Hebreus', bookNum: 58, title: 'Hebreus 5–7',       chapters: '5–7',     section: sections[8], marker: C },
  { day: 269, book: 'Hebreus', bookNum: 58, title: 'Hebreus 8–10',      chapters: '8–10',    section: sections[8], marker: C },
  { day: 270, book: 'Hebreus', bookNum: 58, title: 'Hebreus 11–13',     chapters: '11–13',   section: sections[8], marker: C },
  { day: 271, book: 'Tiago', bookNum: 59,   title: 'Tiago 1–5',         chapters: '1–5',     section: sections[8], marker: C },
  { day: 272, book: '1 Pedro', bookNum: 60, title: '1 Pedro 1–5',       chapters: '1–5',     section: sections[8], marker: C },
  { day: 273, book: '2 Pedro', bookNum: 61, title: '2 Pedro 1–3',       chapters: '1–3',     section: sections[8], marker: C },
  { day: 274, book: '1 João', bookNum: 62,  title: '1 João 1–5',        chapters: '1–5',     section: sections[8], marker: C },
  { day: 275, book: '2 João', bookNum: 63,  title: '2 João',             chapters: '1',       section: sections[8], marker: C },
  { day: 275, book: '3 João', bookNum: 64,  title: '3 João',             chapters: '1',       section: sections[8], marker: C },
  { day: 275, book: 'Judas', bookNum: 65,   title: 'Judas',              chapters: '1',       section: sections[8], marker: C },
  { day: 276, book: 'Apocalipse', bookNum: 66, title: 'Apocalipse 1–3', chapters: '1–3',     section: sections[9], marker: C },
  { day: 277, book: 'Apocalipse', bookNum: 66, title: 'Apocalipse 4–6', chapters: '4–6',     section: sections[9], marker: C },
  { day: 278, book: 'Apocalipse', bookNum: 66, title: 'Apocalipse 7–9', chapters: '7–9',     section: sections[9], marker: C },
  { day: 279, book: 'Apocalipse', bookNum: 66, title: 'Apocalipse 10–13', chapters: '10–13', section: sections[9], marker: C },
  { day: 280, book: 'Apocalipse', bookNum: 66, title: 'Apocalipse 14–16', chapters: '14–16', section: sections[9], marker: C },
  { day: 281, book: 'Apocalipse', bookNum: 66, title: 'Apocalipse 17–19', chapters: '17–19', section: sections[9], marker: C },
  { day: 282, book: 'Apocalipse', bookNum: 66, title: 'Apocalipse 20–22', chapters: '20–22', section: sections[9], marker: C },

  // Extra days: slower pace through the NT and selected Psalms
  { day: 283, book: 'Salmos', bookNum: 19,  title: 'Salmos 1–5',        chapters: '1–5',     section: sections[2], marker: P },
  { day: 284, book: 'Salmos', bookNum: 19,  title: 'Salmos 6–10',       chapters: '6–10',    section: sections[2], marker: P },
  { day: 285, book: 'Salmos', bookNum: 19,  title: 'Salmos 11–15',      chapters: '11–15',   section: sections[2], marker: P },
  { day: 286, book: 'Salmos', bookNum: 19,  title: 'Salmos 16–20',      chapters: '16–20',   section: sections[2], marker: P },
  { day: 287, book: 'Salmos', bookNum: 19,  title: 'Salmos 21–25',      chapters: '21–25',   section: sections[2], marker: P },
  { day: 288, book: 'Salmos', bookNum: 19,  title: 'Salmos 26–30',      chapters: '26–30',   section: sections[2], marker: P },
  { day: 289, book: 'Salmos', bookNum: 19,  title: 'Salmos 31–35',      chapters: '31–35',   section: sections[2], marker: P },
  { day: 290, book: 'Salmos', bookNum: 19,  title: 'Salmos 36–40',      chapters: '36–40',   section: sections[2], marker: P },
  { day: 291, book: 'Salmos', bookNum: 19,  title: 'Salmos 41–45',      chapters: '41–45',   section: sections[2], marker: P },
  { day: 292, book: 'Salmos', bookNum: 19,  title: 'Salmos 46–50',      chapters: '46–50',   section: sections[2], marker: P },
  { day: 293, book: 'Salmos', bookNum: 19,  title: 'Salmos 51–55',      chapters: '51–55',   section: sections[2], marker: P },
  { day: 294, book: 'Salmos', bookNum: 19,  title: 'Salmos 56–60',      chapters: '56–60',   section: sections[2], marker: P },
  { day: 295, book: 'Salmos', bookNum: 19,  title: 'Salmos 61–65',      chapters: '61–65',   section: sections[2], marker: P },
  { day: 296, book: 'Salmos', bookNum: 19,  title: 'Salmos 66–70',      chapters: '66–70',   section: sections[2], marker: P },
  { day: 297, book: 'Salmos', bookNum: 19,  title: 'Salmos 71–75',      chapters: '71–75',   section: sections[2], marker: P },
  { day: 298, book: 'Salmos', bookNum: 19,  title: 'Salmos 76–80',      chapters: '76–80',   section: sections[2], marker: P },
  { day: 299, book: 'Salmos', bookNum: 19,  title: 'Salmos 81–85',      chapters: '81–85',   section: sections[2], marker: P },
  { day: 300, book: 'Salmos', bookNum: 19,  title: 'Salmos 86–90',      chapters: '86–90',   section: sections[2], marker: P },
  { day: 301, book: 'Salmos', bookNum: 19,  title: 'Salmos 91–95',      chapters: '91–95',   section: sections[2], marker: P },
  { day: 302, book: 'Salmos', bookNum: 19,  title: 'Salmos 96–100',     chapters: '96–100',  section: sections[2], marker: P },
  { day: 303, book: 'Salmos', bookNum: 19,  title: 'Salmos 101–105',    chapters: '101–105', section: sections[2], marker: P },
  { day: 304, book: 'Salmos', bookNum: 19,  title: 'Salmos 106–110',    chapters: '106–110', section: sections[2], marker: P },
  { day: 305, book: 'Salmos', bookNum: 19,  title: 'Salmos 111–115',    chapters: '111–115', section: sections[2], marker: P },
  { day: 306, book: 'Salmos', bookNum: 19,  title: 'Salmos 116–118',    chapters: '116–118', section: sections[2], marker: P },
  { day: 306, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (1–8)',   chapters: '119:1-8', section: sections[2], marker: P },
  { day: 307, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (9–16)',  chapters: '119:9-16', section: sections[2], marker: P },
  { day: 308, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (17–24)', chapters: '119:17-24', section: sections[2], marker: P },
  { day: 309, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (25–32)', chapters: '119:25-32', section: sections[2], marker: P },
  { day: 310, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (33–40)', chapters: '119:33-40', section: sections[2], marker: P },
  { day: 311, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (41–48)', chapters: '119:41-48', section: sections[2], marker: P },
  { day: 312, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (49–56)', chapters: '119:49-56', section: sections[2], marker: P },
  { day: 313, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (57–64)', chapters: '119:57-64', section: sections[2], marker: P },
  { day: 314, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (65–72)', chapters: '119:65-72', section: sections[2], marker: P },
  { day: 315, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (73–80)', chapters: '119:73-80', section: sections[2], marker: P },
  { day: 316, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (81–88)', chapters: '119:81-88', section: sections[2], marker: P },
  { day: 317, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (89–96)', chapters: '119:89-96', section: sections[2], marker: P },
  { day: 318, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (97–104)', chapters: '119:97-104', section: sections[2], marker: P },
  { day: 319, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (105–112)', chapters: '119:105-112', section: sections[2], marker: P },
  { day: 320, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (113–120)', chapters: '119:113-120', section: sections[2], marker: P },
  { day: 321, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (121–128)', chapters: '119:121-128', section: sections[2], marker: P },
  { day: 322, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (129–136)', chapters: '119:129-136', section: sections[2], marker: P },
  { day: 323, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (137–144)', chapters: '119:137-144', section: sections[2], marker: P },
  { day: 324, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (145–152)', chapters: '119:145-152', section: sections[2], marker: P },
  { day: 325, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (153–160)', chapters: '119:153-160', section: sections[2], marker: P },
  { day: 326, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (161–168)', chapters: '119:161-168', section: sections[2], marker: P },
  { day: 327, book: 'Salmos', bookNum: 19,  title: 'Salmo 119 (169–176)', chapters: '119:169-176', section: sections[2], marker: P },
  { day: 328, book: 'Salmos', bookNum: 19,  title: 'Salmos 120–130',     chapters: '120–130', section: sections[2], marker: P },
  { day: 329, book: 'Salmos', bookNum: 19,  title: 'Salmos 131–140',     chapters: '131–140', section: sections[2], marker: P },
  { day: 330, book: 'Salmos', bookNum: 19,  title: 'Salmos 141–150',     chapters: '141–150', section: sections[2], marker: P },
  { day: 331, book: 'Provérbios', bookNum: 20, title: 'Provérbios 1–5', chapters: '1–5',     section: sections[2], marker: P },
  { day: 332, book: 'Provérbios', bookNum: 20, title: 'Provérbios 6–10', chapters: '6–10',   section: sections[2], marker: P },
  { day: 333, book: 'Provérbios', bookNum: 20, title: 'Provérbios 11–15', chapters: '11–15', section: sections[2], marker: P },
  { day: 334, book: 'Provérbios', bookNum: 20, title: 'Provérbios 16–20', chapters: '16–20', section: sections[2], marker: P },
  { day: 335, book: 'Provérbios', bookNum: 20, title: 'Provérbios 21–26', chapters: '21–26', section: sections[2], marker: P },
  { day: 336, book: 'Provérbios', bookNum: 20, title: 'Provérbios 27–31', chapters: '27–31', section: sections[2], marker: P },
  { day: 337, book: 'Mateus', bookNum: 40,  title: 'Mateus 1–5',        chapters: '1–5',     section: sections[5], marker: C },
  { day: 338, book: 'Mateus', bookNum: 40,  title: 'Mateus 6–10',       chapters: '6–10',    section: sections[5], marker: C },
  { day: 339, book: 'Mateus', bookNum: 40,  title: 'Mateus 11–15',      chapters: '11–15',   section: sections[5], marker: C },
  { day: 340, book: 'Mateus', bookNum: 40,  title: 'Mateus 16–20',      chapters: '16–20',   section: sections[5], marker: C },
  { day: 341, book: 'Mateus', bookNum: 40,  title: 'Mateus 21–24',      chapters: '21–24',   section: sections[5], marker: C },
  { day: 342, book: 'Mateus', bookNum: 40,  title: 'Mateus 25–28',      chapters: '25–28',   section: sections[5], marker: C },
  { day: 343, book: 'Lucas', bookNum: 42,   title: 'Lucas 1–4',         chapters: '1–4',     section: sections[5], marker: C },
  { day: 344, book: 'Lucas', bookNum: 42,   title: 'Lucas 5–8',         chapters: '5–8',     section: sections[5], marker: C },
  { day: 345, book: 'Lucas', bookNum: 42,   title: 'Lucas 9–12',        chapters: '9–12',    section: sections[5], marker: C },
  { day: 346, book: 'Lucas', bookNum: 42,   title: 'Lucas 13–16',       chapters: '13–16',   section: sections[5], marker: C },
  { day: 347, book: 'Lucas', bookNum: 42,   title: 'Lucas 17–20',       chapters: '17–20',   section: sections[5], marker: C },
  { day: 348, book: 'Lucas', bookNum: 42,   title: 'Lucas 21–24',       chapters: '21–24',   section: sections[5], marker: C },
  { day: 349, book: 'João', bookNum: 43,    title: 'João 1–4',          chapters: '1–4',     section: sections[5], marker: C },
  { day: 350, book: 'João', bookNum: 43,    title: 'João 5–8',          chapters: '5–8',     section: sections[5], marker: C },
  { day: 351, book: 'João', bookNum: 43,    title: 'João 9–12',         chapters: '9–12',    section: sections[5], marker: C },
  { day: 352, book: 'João', bookNum: 43,    title: 'João 13–17',        chapters: '13–17',   section: sections[5], marker: C },
  { day: 353, book: 'João', bookNum: 43,    title: 'João 18–21',        chapters: '18–21',   section: sections[5], marker: C },
  { day: 354, book: 'Atos', bookNum: 44,    title: 'Atos 1–4',          chapters: '1–4',     section: sections[6], marker: C },
  { day: 355, book: 'Atos', bookNum: 44,    title: 'Atos 5–8',          chapters: '5–8',     section: sections[6], marker: C },
  { day: 356, book: 'Atos', bookNum: 44,    title: 'Atos 9–12',         chapters: '9–12',    section: sections[6], marker: C },
  { day: 357, book: 'Atos', bookNum: 44,    title: 'Atos 13–16',        chapters: '13–16',   section: sections[6], marker: C },
  { day: 358, book: 'Atos', bookNum: 44,    title: 'Atos 17–20',        chapters: '17–20',   section: sections[6], marker: C },
  { day: 359, book: 'Atos', bookNum: 44,    title: 'Atos 21–24',        chapters: '21–24',   section: sections[6], marker: C },
  { day: 360, book: 'Atos', bookNum: 44,    title: 'Atos 25–28',        chapters: '25–28',   section: sections[6], marker: C },
  { day: 361, book: 'Romanos', bookNum: 45, title: 'Romanos 1–4',       chapters: '1–4',     section: sections[6], marker: C },
  { day: 362, book: 'Romanos', bookNum: 45, title: 'Romanos 5–8',       chapters: '5–8',     section: sections[6], marker: C },
  { day: 363, book: 'Romanos', bookNum: 45, title: 'Romanos 9–12',      chapters: '9–12',    section: sections[6], marker: C },
  { day: 364, book: 'Romanos', bookNum: 45, title: 'Romanos 13–16',     chapters: '13–16',   section: sections[6], marker: C },
  { day: 365, book: 'Apocalipse', bookNum: 66, title: 'Apocalipse 1–11', chapters: '1–11',   section: sections[9], marker: C },
  { day: 366, book: 'Apocalipse', bookNum: 66, title: 'Apocalipse 12–22', chapters: '12–22', section: sections[9], marker: C },
]

export function getNextUncompletedDay(completedDays: Set<number>): number {
  for (let d = 1; d <= 366; d++) {
    if (!completedDays.has(d)) return d
  }
  return 366
}

export function getReadingForDay(day: number): ReadingDay[] {
  return readingPlan.filter(d => d.day === day)
}

export function getDaysInSection(sectionId: string): ReadingDay[] {
  return readingPlan.filter(d => d.section.id === sectionId)
}

export function getBookVideoUrl(bookNum: number): string | null {
  const slugs: Record<number, string> = {
    1: 'genesis', 2: 'exodo', 3: 'levitico', 4: 'numeros', 5: 'deuteronomio',
    6: 'josue', 7: 'juizes', 8: 'rute', 9: '1-samuel', 10: '2-samuel',
    11: '1-reis', 12: '2-reis', 13: '1-cronicas', 14: '2-cronicas',
    15: 'esdras', 16: 'neemias', 17: 'ester', 18: 'jo', 19: 'salmos',
    20: 'proverbios', 21: 'eclesiastes', 22: 'cantico-de-salomao',
    23: 'isaias', 24: 'jeremias', 25: 'lamentacoes', 26: 'ezequiel',
    27: 'daniel', 28: 'oseias', 29: 'joel', 30: 'amos', 31: 'obadias',
    32: 'jonas', 33: 'miqueias', 34: 'naum', 35: 'habacuque', 36: 'sofonias',
    37: 'ageu', 38: 'zacarias', 39: 'malaquias', 40: 'mateus',
    41: 'marcos', 42: 'lucas', 43: 'joao', 44: 'atos', 45: 'romanos',
    46: '1-corintios', 47: '2-corintios', 48: 'galatas', 49: 'efesios',
    50: 'filipenses', 51: 'colossenses', 52: '1-tessalonicenses',
    53: '2-tessalonicenses', 54: '1-timoteo', 55: '2-timoteo', 56: 'tito',
    57: 'filemom', 58: 'hebreus', 59: 'tiago', 60: '1-pedro', 61: '2-pedro',
    62: '1-joao', 63: '2-joao', 64: '3-joao', 65: 'judas', 66: 'apocalipse',
  }
  const slug = slugs[bookNum]
  if (!slug) return null
  return `https://www.jw.org/pt/biblioteca/videos/introducao-livros-da-biblia/livro-de-${slug}/`
}

export function getWolUrl(bookNum: number, chapter: number): string {
  return `https://wol.jw.org/pt/wol/b/r5/lp-t/nwtsty/${bookNum}/${chapter}`
}

const START_DATE_KEY = 'reading_start_date'

export function isReadingStarted(): boolean {
  return localStorage.getItem(START_DATE_KEY) !== null
}

export function getReadingStartDate(): Date | null {
  const stored = localStorage.getItem(START_DATE_KEY)
  return stored ? new Date(stored) : null
}

export function setReadingStartDate(date: Date): void {
  const d = new Date(date)
  d.setHours(0, 0, 0, 0)
  localStorage.setItem(START_DATE_KEY, d.toISOString())
}

export function clearReadingStartDate(): void {
  localStorage.removeItem(START_DATE_KEY)
}

export function getReadingDayForDate(date: Date): number | null {
  const stored = localStorage.getItem(START_DATE_KEY)
  if (!stored) return null
  const start = new Date(stored)
  start.setHours(0, 0, 0, 0)
  const target = new Date(date)
  target.setHours(0, 0, 0, 0)
  const diffDays = Math.floor((target.getTime() - start.getTime()) / 86400000)
  const day = diffDays + 1
  return day >= 1 && day <= 366 ? day : null
}

export function getDateForReadingDay(day: number): Date | null {
  const stored = localStorage.getItem(START_DATE_KEY)
  if (!stored) return null
  const start = new Date(stored)
  const d = new Date(start)
  d.setDate(d.getDate() + day - 1)
  return d
}

export function getTodayReadingDay(): number | null {
  return getReadingDayForDate(new Date())
}
