[project]
id = "lbgztfqgzjmiwvcghnki"

[functions]
send-daily-reminder = { verify_jwt = false }
bible-agent = { verify_jwt = true }
admin-operations = { verify_jwt = false }
send-admin-notification = { verify_jwt = false }
